[package]
name = "mc-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
futures = "0.3"
reqwest = { version = "0.12", default-features = false, features = ["json", "blocking", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["mods"]
mods = []

[profile.release]
opt-level = "z"     # Optimize for minimal binary size ("s" is also an option for size)
strip = true        # Automatically strip symbols from the binary
lto = true          # Enable Link-Time Optimization for better dead code elimination
codegen-units = 1   # Reduce parallel units to increase optimization potential
panic = "abort"     # Remove stack unwinding code (shrinks size, but no backtraces)
